### ISSUE TITLE
About calculation for CMIP6 projections

### ISSUE THREAD

**Issue by mictomi** [tammasloughran/ehfheatwaves#26]
Hello sir, 

Thank you for making your code available for public use. 

Thank you for making your code available for public use.

Question 1: I would like to compute heat waves for future projections using the CMIP6 dataset. I understand that an historical baseline would be used for the calculation. Could you please confirm if this code is correct? and do I need to specify the" vname" for the projection files? will this code output projection results?

  ehfheatwaves -x  Tmax_hist_CMIP6.nc --bpfx=Tmax_Future_CMIP6.nc  -n Tmin_hist_CMIP6.nc --bpfn=Tmin_Future_CMIP6.nc  
 --vnamex=tasmax --vnamen=tasmin --base=1961-1990 --t90pc -v

These are the historical ("Tmax_hist_CMIP6.nc", "Tmin_hist_CMIP6.nc") and projection ("Tmax_Future_CMIP6.nc", "Tmin_Future_CMIP6.nc") files.

Question 2: Some percentile calculations are based on a 5-day window; can I simply change "wsize:int=15" to "5" inside ehfheatwaves.py? any implication with such changes?

Question 3: Aside from running the code in Question 1, are there any other calculations I need to do? For instance, there is "percent_summer.py" inside the "contrib' folder.

Question 4: If I am using a regional dataset, say over United States, does the program automatically recognize this and focus calculations only on extended summer (May–September) or do my inputs have to be May–September datasets?

I would appreciate your response.

Thank you

**Comment by tammasloughran** [comment]
> `ehfheatwaves -x Tmax_hist_CMIP6.nc --bpfx=Tmax_Future_CMIP6.nc -n Tmin_hist_CMIP6.nc --bpfn=Tmin_Future_CMIP6.nc
--vnamex=tasmax --vnamen=tasmin --base=1961-1990 --t90pc -v`

No, that would be wrong. The temperature data that will be used to calculate the base period should be passed to the `--bpfn` and `--bpfx` arguments. You have them around the wrong way. It should be:

`ehfheatwaves -x Tmax_Future_CMIP6.nc --bpfx=Tmax_hist_CMIP6.nc -n Tmin_Future_CMIP6.nc --bpfn=Tmin_hist_CMIP6.nc
--vnamex=tasmax --vnamen=tasmin --base=1961-1990 --t90pc -v`

> can I simply change "wsize:int=15" to "5" inside ehfheatwaves.py? any implication with such changes?

Yes, that should be fine. You would need to install the modified version. Be aware that there may be more random noise in the climatology.

>  If I am using a regional dataset, say over United States, does the program automatically recognize this and focus calculations only on extended summer (May–September) or do my inputs have to be May–September datasets?

Yes. It will recognise which hemisphere the data are in and define summer (northern hemisphere May–September) and winter (northern hemisphere November–March) accordingly. There is no way to easily specify an arbitrary season period. For example, many tropical periods do not align with this definition. You can output daily heatwave indicators (e.g. `--tx90pc-daily`) and aggregate statistics over any period yourself if need be.

**Comment by mictomi** [comment]
Thank you

**Comment by mictomi** [comment]
Hi, 

I ran the code as corrected

ehfheatwaves -x tasmax_day_ACCESS-CM2_ssp585_r1i1p1f1_gn_2015-2099.nc --bpfx=tasmax_day_ACCESS-CM2_historical_r1i1p1f1_gn_1951-2014.nc -n tasmin_day_ACCESS-CM2_ssp585_r1i1p1f1_gn_2015-2099.nc --bpfn=tasmin_day_ACCESS-CM2_ssp585_r1i1p1f1_gn_2015-2099.nc --vnamex=tasmax --vnamen=tasmin --base=1961-1990 --t90pc -v

but I got this error
===========================================
Loading data
Traceback (most recent call last):
  File "/home/mictomi/anaconda3/bin/ehfheatwaves", line 8, in <module>
    sys.exit(main())
  File "/home//anaconda3/lib/python3.7/site-packages/ehfheatwaves/ehfheatwaves.py", line 392, in main
    tave_base = (tmax + tmin)/2.
  File "/home/mictomi/anaconda3/lib/python3.7/site-packages/numpy/ma/core.py", line 4139, in __add__
    return add(self, other)
  File "/home/mictomi/anaconda3/lib/python3.7/site-packages/numpy/ma/core.py", line 1015, in __call__
    result = self.f(da, db, *args, **kwargs)
ValueError: operands could not be broadcast together with shapes (10950,64,128) (0,1,1)

**Comment by tammasloughran** [comment]
The tasmin base period file is the future ssp585 scenario. I think it should be 
`tasmin_day_ACCESS-CM2_historical_r1i1p1f1_gn_1951-2014.nc`

**Comment by tammasloughran** [comment]
There was a change in the NetCDF4 python library recently that allows you to index NetCDF variable objects with an empty array. I asked them to not allow this because it causes errors that are hard to diagnose. In this case, it has indexed the NetCDF object with a base period that does not exist in the file, so it returns nothing and thus we see (0,1,1) in the tmin data.

**Comment by mictomi** [comment]
It worked. Thank you for your observation and assistance.
