### ISSUE TITLE
Trouble with time format? 

### ISSUE THREAD

**Issue by arijoury** [tammasloughran/ehfheatwaves#29]
Hi,

I'm trying to run the module using NetCDF input files that I created. I made sure that the time is formatted as a timestamp and that my base period is in the files. This is the command I use to try to run the code:
`ehfheatwaves -x "../hist_daily_Tmax_Balsas.nc" -n "../hist_daily_Tmin_Balsas.nc" --base=1991-2020 -d` 

I'm getting the following error:
`/opt/homebrew/lib/python3.11/site-packages/ehfheatwaves/getoptions.py:86: UserWarning: You didn't specify a land-sea mask. It's faster if you do, so this might take a while.
  if not options.maskfile: warnings.warn(warnmsg, UserWarning)
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/ehfheatwaves/ncio.py", line 180, in load_bp_data
    temp = tempnc.variables[varname][(options.bpstart<=bpdates.year)&(bpdates.year<=options.bpend)]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/netCDF4/_netCDF4.pyx", line 4934, in netCDF4._netCDF4.Variable.__getitem__
  File "/opt/homebrew/lib/python3.11/site-packages/netCDF4/utils.py", line 243, in _StartCountStride
    raise IndexError(msg)
IndexError: 
Boolean array must have the same shape as the data along this dimension.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/ehfheatwaves", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ehfheatwaves/ehfheatwaves.py", line 388, in main
    tmax = ncio.load_bp_data(options, timedata, variable='tmax', mask=mask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ehfheatwaves/ncio.py", line 182, in load_bp_data
    raise IndexError(
IndexError: Could not index netCDF file time dimension. This could be a calendar problem. Please make sure your input file is daily frequency data and/or that it contains the base period. You wanted 1991-2020 and your data have 1987-2021`

I'm can't append the .nc files, so I'm appending the csv files that I used to make them.
[hist_daily_Tmax_Balsas.csv](https://github.com/tammasloughran/ehfheatwaves/files/12417676/hist_daily_Tmax_Balsas.csv)
[hist_daily_Tmin_Balsas.csv](https://github.com/tammasloughran/ehfheatwaves/files/12417677/hist_daily_Tmin_Balsas.csv)

For traceability, here's how I converted the csv to nc files, using Python:
`import xarray
import pandas as pd

dfmin = pd.read_csv('hist_daily_Tmin_Balsas.csv')
dfmax = pd.read_csv('hist_daily_Tmax_Balsas.csv')
xrmin = xarray.Dataset.from_dataframe(dfmin)
xrmax = xarray.Dataset.from_dataframe(dfmax)
xrmin.to_netcdf('hist_daily_Tmin_Balsas.nc')
xrmax.to_netcdf('hist_daily_Tmax_Balsas.nc')
`

Any help is appreciated! Thanks in advance.

**Comment by tammasloughran** [comment]
The netcdf files you produce are malformed, and I could only guess that the dates are not being associated with the data properly. NetCDF is designed for gridded data so you need to think like a grid. :)
Here is an example of how to convert to netcdf.
```python
#!/usr/bin/env python3
import numpy as np
import netCDF4 as nc

# Load data.
data = np.genfromtxt('hist_daily_Tmax_Balsas.csv', delimiter=',')
as_strings = np.genfromtxt('hist_daily_Tmax_Balsas.csv', delimiter=',', dtype=np.str)
# Remove header.
data = data[1:,:]
as_strings = as_strings[1:,:]
# Index columns into variables.
lon = data[0,0]
lat = data[0,1]
timestamps = as_strings[:,2]
tmax = data[:,3]

# Create NetCDF file.
ncfile = nc.Dataset('tmax.nc', mode='w')
ncfile.createDimension('lon', size=1) # There is only 1 station
ncfile.createDimension('lat', size=1) # There is only 1 station
ncfile.createDimension('time', size=None) # None sets the time dimension to 'unlimited'. Usefull if you want to concatenate data if more comes available in the future.
# The below commands define the variables and the dimensions they use.
nclon = ncfile.createVariable('lon', np.float, dimensions=('lon'))
nclat = ncfile.createVariable('lat', np.float, dimensions=('lat'))
nctimes = ncfile.createVariable('time', np.str, dimensions=('time'))
nctmax = ncfile.createVariable('tmax', np.float, dimensions=('time','lat','lon'))
# The below commands assign which data in ram is the corresponding netcdf variable.
nclon[:] = lon
nclat[:] = lat
nctimes[:] = timestamps
nctmax[:] = tmax
# Then flush to write to disk
ncfile.close()
```

It might actually save you some trouble to use Climpact instead of ehfheatwaves, because it can handle .csv files.
https://climpact-sci.org/

Cheers,
Tam

**Comment by arijoury** [comment]
That's pretty awesome, thanks! Your solution works, and I've bookmarked Climpact for future use too.

Thanks for your help!

Ari
